mqtt:
    server: localhost
    # user: 
    # pwd: 
    retain_config: true

ble:
    device: hc0


web_admin:
    enabled: true
    port: 8080

devices:
    - name: flora
      id: 0x18155d287bf4
    - name: reflora
      id: 0xc405005985679812

